// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9oqTDPEGaEQI3QVsCogNHtHQ8_zyA0QE',
    appId: '1:667915788099:web:9e98b221886087987559f6',
    messagingSenderId: '667915788099',
    projectId: 'my-mail-client-demo',
    authDomain: 'my-mail-client-demo.firebaseapp.com',
    storageBucket: 'my-mail-client-demo.appspot.com',
    measurementId: 'G-5E7KWMH887',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT9rItbt1bWBugIdL9eZbE7EGWZ5FTlHA',
    appId: '1:667915788099:android:197fdd52303c0b637559f6',
    messagingSenderId: '667915788099',
    projectId: 'my-mail-client-demo',
    storageBucket: 'my-mail-client-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbdsfjekl0cKJCq_0SOoTqA2bGT8R8Hlk',
    appId: '1:667915788099:ios:4f1ded4ca5912ce07559f6',
    messagingSenderId: '667915788099',
    projectId: 'my-mail-client-demo',
    storageBucket: 'my-mail-client-demo.appspot.com',
    iosBundleId: 'com.example.mailLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbdsfjekl0cKJCq_0SOoTqA2bGT8R8Hlk',
    appId: '1:667915788099:ios:4f1ded4ca5912ce07559f6',
    messagingSenderId: '667915788099',
    projectId: 'my-mail-client-demo',
    storageBucket: 'my-mail-client-demo.appspot.com',
    iosBundleId: 'com.example.mailLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9oqTDPEGaEQI3QVsCogNHtHQ8_zyA0QE',
    appId: '1:667915788099:web:e846c063bf40171c7559f6',
    messagingSenderId: '667915788099',
    projectId: 'my-mail-client-demo',
    authDomain: 'my-mail-client-demo.firebaseapp.com',
    storageBucket: 'my-mail-client-demo.appspot.com',
    measurementId: 'G-D3MEJCQ8Z7',
  );
}
